# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 88febd212fb7fc82d7c0398dba63b4010d086b637ffe8bb97355b25c54816ed26120a7d03c7f3a5f31d320070276f37d77d4ee2c67b24b1e60862edd0fc6dc2f

test:
  secret_key_base: 3667208e13727d09313a8eefa9674f0ff1106cf36cf48e3c9e2b1bfdcff747acc90c7b1948ed317bd922c4ecfd02818e993efba37b932a13422c9c482ccd0a3b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
